### ISSUE TITLE
Unable to get purchased items (on multiple devices using the same Google account)

### ISSUE THREAD

**Issue by josephmesteban** [serso/android-checkout#122] opened 2017-10-16 11:06 UTC
My case is similar to an already closed issue #15 

On device#A, I purchased an item(XYZ) but was not able to consume due to some conditions unique to our specification. On device#A, I check if item(XYZ) has been purchased, and if it is, I simply consume it. There is nothing abnormal in this scenario as I was able to get the list of purchased items. The issue is when I use device#B (with same Google account). When that same method  that checks if item(XYZ) has been purchased would not correctly return the purchased item(s). Subsequently, when user tries to buy item(XYZ), an error indicating the item is already owned pops up. 

I have tried returning null on Billing.Configuration#getCache method or clearing the cache withCache#clear method as proposed but to no avail.

#issue 15 is already marked closed, yet, there seems to be another person having the same issue as I am dealing with. 

I simply want to be able to check if an Item is already purchased (so I can just consume it) across devices (with same account). 

I would appreciate if you could assist me to a proper solution.

**Comment by serso** [comment] 2017-10-22 18:32
This scenario should work. I myself have tested the same account on different devices and the list of purchased items was the same on all of them. Can you please share some code to reproduce the issue?

**Comment by josephmesteban** [comment] 2017-10-23 01:26
Thank you for responding! 
Here's my method that checks if an item is already purchased and therefore should be consumed.

```
public void canConsumeSku(final String skuIdentifier, final CanConsumeSkuCallback canConsumeSkuCallback) {
        if (canConsumeSkuCallback == null) {
            return;
        }
        final Inventory.Request request = Inventory.Request.create();
        request.loadAllPurchases();
        request.loadSkus(ProductTypes.IN_APP, skuIdentifier);
        checkout.loadInventory(request, new InventoryCallback() {
            @Override
            public void onLoaded(@Nonnull Inventory.Products products) {
                final Inventory.Product product = products.get(ProductTypes.IN_APP);
                if (product.supported) {
                    final List<Purchase> purchases = product.getPurchases();
                    if (purchases.size() > 0) {
                        if (purchases.get(0).sku.equals(skuIdentifier)) {
                            canConsumeSkuCallback.onCanConsumeStatus(true);
                        }
                    }
                    canConsumeSkuCallback.onCanConsumeStatus(false);
                }
                canConsumeSkuCallback.onCanConsumeStatus(false);
            }
        });
}
```

As mentioned in my ticket, this method works as expected in the device where an Item was purchased (but not consumed). However, in another device, this method always returns an empty list ('purchases' list in the above code). I suspected that the underlying cache might be the culprit. However, clearing the cache and/or returning null in Billing.Configuration#getCache does not solve the problem. 

BTW, I am testing my app to an alpha/beta channel, and was wondering if you did the same on the tests you mentioned.

I really appreciate you help!

**Comment by serso** [comment] 2017-10-23 07:53
If the issue is reproduced even when you return `null` from `Billing.Configuration#getCache` I doubt it is caused by the cache. Even with the cache enabled loaded purchases stay in the cache only for 20 minutes and a new request to the billing API is done after they have expired.

There is one problem in your
 code: you should check the purchase state before calling `CanConsumeSkuCallback#onCanConsumeStatus`
https://github.com/serso/android-checkout/blob/5b84d50a19a499ef0f44ab8e84001748f7bab90f/lib/src/main/java/org/solovyev/android/checkout/Purchase.java#L54

Regarding the alpha/beta channel: I don't know if the purchases done in these channels are handled by Google in the same way as in the final channel (for example the information might not be shared between several devices, etc)

You can also try the sample app and see if you can reproduce the problem: https://play.google.com/store/apps/details?id=org.solovyev.android.checkout.app
You can build it from the source, change the package name, upload to your account and try to reproduce the issue.

**Comment by josephmesteban** [comment] 2017-10-23 08:11
Thanks for pointing the error regarding `Purchase#state` .

Why do you think the problem disappears when I restart the device? 

 I will investigate further and check If I can reproduce it with the sample app.

**Comment by serso** [comment] 2017-10-23 08:22
I don't know to be honest. My guess is that Google Play Services (aka the billing API) re-fetches billing data from the servers after device reboot.

Note regarding the cache: this library uses a simple in-memory cache (20 minutes expiration time for purchases). The billing API might use its own cache which we, developers, can't get hold of. It's also unknown how this cache behaves as the implementation of billing API is a proprietary code from Google.

**Comment by josephmesteban** [comment] 2017-10-23 09:15
Thank you for your answer, especially for clarifying about cache. I will keep you posted. Cheers!

**Comment by serso** [comment] 2017-11-06 09:04
@josephmesteban have you figured out what caused the issue? Can it be fixed in the library? Or is it a limitation of the billing API?

**Comment by josephesteban** [comment] 2017-11-07 00:31
I am sorry for the late response! We currently don't have a fix/workaround for this issue yet.

**Comment by serso** [comment] 2017-11-07 08:45
@josephesteban no problem. You can try to reproduce the problem with Google's Trivial Drive app. If it doesn't work either then you can submit a bug report to them.

**Comment by josephesteban** [comment] 2017-11-09 01:15
@serso Hi! This is apparently a limitation of Google's billing API so I think this cannot be fixed in the library. I think one way to solve this to save in-app purchases on a server for more accurate queries later on.

Here is a link of a discussion similar to this issue:
https://stackoverflow.com/questions/42992369/in-app-purchase-two-devices-with-same-account-not-getting-same-purchased-items

**Comment by serso** [comment] 2017-11-09 08:24
@josephesteban thank you for investigating this. Yes indeed, it seems that it's a limitation of the billing API.
I'm closing the issue now.

**Closed by serso** 2017-11-09 08:24 UTC
