### ISSUE TITLE
onLoaded called, list of Products (sometimes) empty

### ISSUE THREAD

**Issue by peterhav** [serso/android-checkout#74] opened 2017-02-01 09:45 UTC
First of all: thanks for this great library.
I encounter the following situation: in some situations the onLoaded is called but the list of products is empty. Note that this does not happen in all situation: I only get an exception report from a small number of users.
What could be causing this? I assumed that in case of onLoaded being called, there would always be a complete inventory available?
Thanks for any help.

**Comment by serso** [comment] 2017-02-01 10:10
> in some situations the onLoaded is called but the list of products is empty.
How do you know that? Do you log the it somewhere? The problem might be in the code handles the result.
> What could be causing this?
I don't know unless you provide some code.
> I assumed that in case of onLoaded being called, there would always be a complete inventory available?
What version of the library do you use? Are you talking about SKUs or purchases?

**Comment by peterhav** [comment] 2017-02-01 10:50
This is the relevant part of the code:

```
@Override
        public void onLoaded(@NonNull Inventory.Products products) {
            setBillingButtonEnabled( true );

            logBilling("in onLoaded");
            logBilling("  inventory: " + products.get( SUBSCRIPTION ).getSkus().size() + " purchaseable subscription product(s)");

            mPurchaseableItems = products.get(SUBSCRIPTION).getSkus();

            if (mPurchaseableItems.size() == 0 && !Utils.isDebug( MainActivity.this )) {
                    FirebaseCrash.report(new Exception("onLoaded called with empty inventory. ( " + uid + " )"));
            }
```

I'm receiving the FirebaseCrash report (which I would not expect). I'm sure that there are SUBSCRIPTION SKU's for this app: on my personal and other users devices the products are correctly showing.

**Comment by serso** [comment] 2017-02-01 12:00
How do you request Inventory?

**Comment by peterhav** [comment] 2017-02-01 12:33
The method `reloadInventory(); ` is called within my `onCreate` and in the `PurchaseListener`: 

```
private void reloadInventory() {
        final Inventory.Request request = Inventory.Request.create();
        request.loadPurchases(SUBSCRIPTION);
        request.loadSkus(SUBSCRIPTION, BillingConst.getAllPurchasableSkus());
        mCheckout.loadInventory(request, new InventoryCallback());
    }
```

BillingConst: 

```
public static ArrayList<String> getAllPurchasableSkus(){
        ArrayList<String> r = new ArrayList<>();
        r.add( SKU_BASIC_SUBSCRIPTION_VIP_1 );
        r.add( SKU_BASIC_SUBSCRIPTION_VIP_YEARLY_1 );
        r.add( SKU_BASIC_SUBSCRIPTION_1 );
        r.add( SKU_BASIC_SUBSCRIPTION_YEARLY_1 );
        r.add( SKU_FULL_SUBSCRIPTION_1 );
        r.add( SKU_FULL_SUBSCRIPTION_YEARLY_1 );
        r.add( SKU_FULL_SUBSCRIPTION_VIP_1 );
        r.add( SKU_FULL_SUBSCRIPTION_VIP_YEARLY_1 );
        return r;
    }
```

**Comment by serso** [comment] 2017-02-01 13:18
The code looks fine. On the other hand the list of SKUs might be empty if for example there is no internet connection. Maybe you can check this in the crash reports?

**Comment by peterhav** [comment] 2017-02-01 13:25
In the Crash report I see that there is a WIFI connection (could of course still be without internet...). 

In the library code I see in the comments on the `onLoaded` method that it will always be called (even in case of problems). Would it be wise to report problems as an argument to the method? 
In that case user could disable the "Billing" and show the end-user the cause for this.

**Comment by serso** [comment] 2017-02-03 08:13
To be honest, I have no idea why the SKU list is empty. Is there any pattern in the crash reports that can give us some hint? Maybe it's all custom ROMs? Specific phone model/manufacturer? Android version?
How many reports do you get relatively to the total number of users? Is it like 1%? Less? More?

**Comment by peterhav** [comment] 2017-02-03 12:36
@serso, this currently happened 2 times, for a single user (in my app's beta there are around 400 involved users). The device is a 'Xiaomi', so I expect this has to do with the Play store not being available.
I will perform the `setBillingButtonEnabled` once I see that the list of items is available. If I get much more Crash reports (from other device types) I will report this here. Thanks for the quick response.

**Comment by serso** [comment] 2017-02-03 15:12
OK, I'll close this issue for now. Feel free to reopen it again if you have more details or it affects a lot of users.

**Comment by peterhav** [comment] 2017-02-13 08:47
Hello, at this moment I have multiple users that encountered this issue. In the logs I see that in some cases there is no internet connection, but in others there is (70%/30%). 
In the period that I'm using this library, 2% of the users encountered this issue. I happens on regular devices: Nexus 5, Samsung (SM-G935F, GT-I9195) and Motorola G3.

**Comment by serso** [comment] 2017-02-13 11:49
So 70% of reports come when there is no internet connection, right?
It might be that other 30% happen:
1. When a connection has just been established (or lost)
2. When requests from Google Play Services are blocked
3. Due to some weird custom ROM

What's the total number of affected users? Can you contact any of them and ask to reproduce the problem?

**Comment by rpattabi** [comment] 2017-02-13 12:32
I have no experience with this library. But just curious.

I know Google Play caches products and purchases once retrieved. So most of the times, there is no need to have internet connection.

I wonder if this problem happens at the first attempt or for later retrieval.

**Comment by peterhav** [comment] 2017-02-13 20:09
Hi @serso, the analytics mechanism is anonymous, so no way to contact the users that encounter this issue directly. I have added another analytics call to measure the percentage of users that have successfully loaded the pricing details at least once. This should clarify the situation; I will post results after some time once I have the metrics available (I would expect this to get close to 100%, since users require both Google Play and internet access to be able to download and install the app).

**Comment by serso** [comment] 2017-02-22 20:46
Any updates on this, @peterhav?

**Comment by peterhav** [comment] 2017-02-23 16:21
I've got some results, but I'm not 100% confident on how to analyse them... 

The results of last week:
Nr of app session starts (last week): 90
Nr of 'inventory loaded at least once': 77
I did not get any complaints on users that wanted, but could not access the inventory.

The 'inventory loaded at least once' user property that is set to true when the app loads the inventory successfully.

Warning: it could be that the 77 are only the users that loaded the inventory for the first time in the last week (and not the ones that loaded it already before last week). 
Furthermore I don't know how the analytics tool handles the case in which the value is set multiple times (my assumption would be that this only shows as 1). Next to this, the app-session trigger does not mean that the inventory load takes place (since this happens in a later activity...). 
Conclusion: I need to improve the analytics in the app to get better figures, but this will take some time. As long as I do not get complains from users I'm not to worried about this.

**Comment by serso** [comment] 2017-03-10 08:15
I'll close the issue for now.

**Closed by serso** 2017-03-10 08:15 UTC
Labels: help wanted

**Comment by pawelantczak** [comment] 2017-11-30 18:10
@peterhav do you have any further thoughts?
I'm suffering from exactly same issue.
Some people are complaining about 'pro' version not recognized on new device - which can be related to first sku sync.
More disturbing are cases, where user is logged off (pro not recognized) after some time - which means, skus list was received correctly before.

**Comment by rpattabi** [comment] 2017-12-01 04:37
@pawelantczak This could also be related to using cache cleaner apps. Just like virus scanners on windows, android users are accustomed to cache cleaners in the need of saving storage space. Some of these apps cleans even Google play app cache. So it isn't surprising that Google Play may be yet to retrieve purchases or takes longer than usual depending on the internet connection.

**Comment by pawelantczak** [comment] 2017-12-01 16:36
@rpattabi Thanks. You may be right.

**Comment by petrovichtim** [comment] 2017-12-09 05:16
Список продуктов пустой, потому что гугл отключает покупки для разработчиков
