### ISSUE TITLE
Crash on emulator devices, Listener already in list

### ISSUE THREAD

**Issue by pyamsoft** [serso/android-checkout#69] opened 2016-12-28 19:31 UTC
Hello,

I have observed a crash caused by this library (0.9.1) on emulator devices. 
This crash may possibly extend to all devices which do not have Google Play
Billing support.

It seems that the library attempts to register duplicate Google Play update 
listeners, and crashes. I have created a simple project which shows this 
behavior on at least two emulator devices running KitKat and Lollipop. 
Both emulators do not support Google Play billing. I can confirm that the 
exact same code running on a real device with Google Play billing capability 
does not crash. I have not been able to test if the code running on a real 
device that does not support billing will also crash.

https://github.com/pyamsoft/android-checkout-crashreport

**Comment by serso** [comment] 2016-12-28 23:30
I'll release a new version of the library soon. Meanwhile, you can try the source code from the master branch and check that the issue has been resolved.

**Comment by skywave** [comment] 2017-01-12 18:13
This fix does seem to come with a unwanted side-effect, crashes sometimes with 

"State DISCONNECTING can't come right after CONNECTING state" 

> org.solovyev.android.checkout.Check.isMainThread (Unknown Source)
org.solovyev.android.checkout.Billing.error (Unknown Source)
org.solovyev.android.checkout.Billing.disconnect (Unknown Source)
org.solovyev.android.checkout.Billing.onCheckoutStopped (Unknown Source)
org.solovyev.android.checkout.Checkout.forActivity (Unknown Source)
org.solovyev.android.checkout.ActivityCheckout.stop (Unknown Source)
ListActivity.onDestroy (Unknown Source)

Different path:

>Fatal Exception: f.a.a.a.l$a: State DISCONNECTING can't come right after CONNECTING state
       at org.solovyev.android.checkout.Check.isMainThread(Unknown Source)
       at org.solovyev.android.checkout.Billing.error(Unknown Source)
       at org.solovyev.android.checkout.Billing.error(Unknown Source)
       at org.solovyev.android.checkout.Billing$DefaultServiceConnector$1.onServiceDisconnected(Unknown Source)
       at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1469)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1483)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)



Not being able to replicate directly, but i presume the first one occurs leaving an activity before the CONNECTED state is established.

**Comment by loki666** [comment] 2017-01-23 18:06
I'm having the same issues with my apps, any progress ?

**Comment by serso** [comment] 2017-01-28 16:04
Sorry for the late response, didn't have time to investigate this assertion failure. Will take a look tomorrow evening.

From the stack trace it seems that this is not a regression in behavior but rather it is due to the stricter rules that were introduced recently. In other words, if you strip all Checks with Proguard the app should work as it worked before.

**Comment by serso** [comment] 2017-01-28 16:15
I believe this issue has the same cause as #72. Probably will be fixed together

**Closed** 2017-01-29 21:11 UTC
