### ISSUE TITLE
Inventory is already loaded Exception

### ISSUE THREAD

**Issue by gowong** [serso/android-checkout#38] opened 2015-06-03 04:09 UTC
I recently started using this library. Since releasing to live, I'm seeing quite a few crashes with the attached stack trace. Any ideas what would cause this?

```
c.b.a.a.ai: Inventory is already loaded. Loading id: 1
       at org.solovyev.android.checkout.Check.isFalse(SourceFile:104)
       at org.solovyev.android.checkout.CheckoutInventory$Counter.countDown(SourceFile:194)
       at org.solovyev.android.checkout.CheckoutInventory.onFinished(SourceFile:72)
       at org.solovyev.android.checkout.CheckoutInventory.onFinished(SourceFile:67)
       at org.solovyev.android.checkout.CheckoutInventory$ProductRequestListener.onError(SourceFile:120)
       at org.solovyev.android.checkout.RequestListenerWrapper.onError(SourceFile:43)
       at org.solovyev.android.checkout.Billing$CachingRequestListener.onError(SourceFile:948)
       at org.solovyev.android.checkout.Request.start(SourceFile:147)
       at org.solovyev.android.checkout.Request.start(SourceFile:140)
       at org.solovyev.android.checkout.Billing$OnConnectedServiceRunnable.run(SourceFile:615)
       at org.solovyev.android.checkout.PendingRequests.run(SourceFile:155)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by serso** [comment] 2015-06-04 08:43
This looks strange and should not normally happen. Do you have an open-source app? Can you share the source code?
Meanwhile, you can add this to your proguard configuration:
```
-assumenosideeffects class org.solovyev.android.checkout.Check {
        *;
}
```
This will prevent the crash and should not affect anything else.

**Comment by gowong** [comment] 2015-06-05 03:57
Thanks for looking into this.
My app isn't open source, but I made a gist of the relevant parts.
https://gist.github.com/gowong/2eac5fbd1e0884a933c1

**Comment by serso** [comment] 2015-06-24 09:32
I still can't figure out how this might happen. It seems there was some billing error before the crash (in the stack trace onError method is called), do you know what kind of error is that?
I also added a unit test simulating billing crashing but it doesn't cause assertion failure: 358600ca384f7894f37920e2bca160e92509c4c9
Do you have any information about devices/Android versions where the crash appears?

**Comment by gowong** [comment] 2015-06-25 05:36
I don't know what the billing error is. Does Checkout propagate that error in some way? If so, I can add some logging to help investigate further. I have crash reports that I can share with you. http://crashes.to/s/2c6eccc955a
My app supports Android 4.0 and higher so it's a bit surprising that most of the crashes are happening on Android 5.x

**Comment by serso** [comment] 2015-06-25 13:54
I finally found the problem! It seems that crash happens in your code (in one of Inventory.Listener) which causes RequestListener.onError to be called right after RequestListener.onSuccess is called (this was quite a surprising behavior, now fixed here 69562b2e1a260d1bd0fa0c86bfa5f18e43476313).
After 2811d48652085a67ad3a7e09ad3aa03302a13756 Checkout assertion error should be gone (basically all exceptions from Inventory listeners are now muted).

Changes above fix Checkout library code but there is definitely something wrong in your app. I recommend you to check all Inventory listeners implementations.

**Comment by serso** [comment] 2015-06-25 14:12
0.7.4 should be available now in repository, please try it and confirm that the problem is gone.

**Comment by gowong** [comment] 2015-06-26 03:33
Thanks for figuring out the issue! I'll try out the new version in my next release and let you know if it worked.

**Comment by serso** [comment] 2015-07-06 09:00
I guess the problem is fixed, please reopen if not

**Closed by serso** 2015-07-06 09:00 UTC
